app:
  db:
    host: 1.94.99.241
    port: 13306
    username: root
    password: 1234+asdf
    catalog: test
  dataLocation: /Users/gukt/data/hello-spring
  upload-dir: ${app.dataLocation}/upload
---
debug: false
spring:
  application:
    name: hello-spring
  datasource:
    username: ${app.db.username}
    password: ${app.db.password}
    url: jdbc:mysql://${app.db.host}:${app.db.port}/${app.db.catalog}?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
# https://docs.spring.io/spring-boot/reference/features/logging.html
logging:
  file:
    name: app
    path: ${app.dataLocation}/logs
  threshold:
    console: debug
    file: debug
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 100GB
  level:
    root: info
    web: info
    sql: error
    com.example: debug
  pattern:
    # 去掉默认 Pattern 中的 PID，Application Name, 以及仅显示日期部分，减少信息冗余。
    # 默认 Pattern 在 classpath:org/springframework/boot/logging/logback/defaults.xml 文件中定义，也可以打开下列地址查看：
    # https://github.com/spring-projects/spring-boot/blob/v3.3.0/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml
    # MDC support: https://logback.qos.ch/manual/mdc.html

    console: "%clr(%d{HH:mm:ss.SSS}){faint} [%thread] %clr(%-5level) %clr([%logger{36}]){cyan} %clr(%X{userId}){magenta} %clr(%X{username}){blue} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} %X{userId} %X{username} - %msg%n"